name: Android Build

on:
  push:
    branches:
      - master  # Changed from 'main' to 'master'
  pull_request:
    branches:
      - master  # Changed from 'main' to 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adoptopenjdk'  # Specify the JDK distribution

    - name: Set up Android SDK
      run: |
        sudo apt update
        sudo apt install -y wget unzip
        wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
        unzip commandlinetools-linux-7583922_latest.zip -d $HOME/android-sdk
        echo "y" | $HOME/android-sdk/tools/bin/sdkmanager --licenses
        $HOME/android-sdk/tools/bin/sdkmanager "platform-tools" "build-tools;30.0.3" "platforms;android-30"

    - name: Build with Gradle
      run: ./gradlew build --no-daemon --stacktrace

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: app/build/outputs/**/*.apk
